# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
  
# Required
version: 2
# Build documentation in the "docs/" directory with Sphinx
python:
  install:
    - method: pip
      path: ./docs
    - requirements: ./docs/requirements.txt

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py